services:
  redis:
    image: redis:7-bookworm
    ports:
      - 6379:6379
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 50
  rmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - check_running
        - -q
      interval: 3s
      timeout: 3s
      retries: 50
  minio:
    image: "bitnami/minio:2025.2.7"
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test:
        - CMD
        - curl
        - http://localhost:9000/minio/health/live
      interval: 3s
      timeout: 1s
      retries: 30
    environment:
      MINIO_DEFAULT_BUCKETS: "rustus"
      MINIO_ROOT_USER: "rustus-test"
      MINIO_ROOT_PASSWORD: "rustus-test"
  kafka:
    image: bitnami/kafka:3.9-debian-12
    healthcheck:
      test:
        - CMD
        - kafka-topics.sh
        - --list
        - --bootstrap-server
        - localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - 9094:9094
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_KRAFT_CLUSTER_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  nats:
    image: nats:2.10-alpine
    ports:
      - 4222:4222
    command: [-m, "8222", "--jetstream"]
    healthcheck:
      test:  
        - "CMD"
        - sh
        - -c
        - "wget http://localhost:8222/healthz -q -O - | xargs | grep ok || exit 1"
      interval: 5s
      timeout: 3s
      retries: 20
     

